name: Hal 9000 - Approve and Create Branch

on:
  workflow_call:
    inputs:
      issue_number:
        description: 'Issue number to approve'
        required: true
        type: number
    secrets:
      PAT_TOKEN:
        required: true
        description: 'Personal access token with repo write permissions'

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout consuming repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout central actions repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/hal9000-actions
          path: .hal9000
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r .hal9000/scripts/requirements.txt

      - name: Fetch changes from branch
        run: |
          CHANGES_BRANCH="hal9000/changes-issue-${{ inputs.issue_number }}"
          mkdir -p .hal9000-output
          
          # Fetch the changes branch
          git fetch origin "$CHANGES_BRANCH"
          
          # Extract files from that branch
          git checkout "origin/$CHANGES_BRANCH" -- . 2>/dev/null || true
          
          # Move to output directory
          mv response.json .hal9000-output/ 2>/dev/null || true
          mv changes.json .hal9000-output/ 2>/dev/null || true
          mv explanation.md .hal9000-output/ 2>/dev/null || true
          
          # Return to main branch
          git checkout main -- . 2>/dev/null || git checkout master -- . 2>/dev/null || true
          
          echo "Changes fetched from branch: $CHANGES_BRANCH"
          ls -la .hal9000-output/

      - name: Apply changes and create branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python .hal9000/scripts/create_branch.py \
            --issue-number ${{ inputs.issue_number }} \
            --output-dir ".hal9000-output" \
            --repo ${{ github.repository }}

      - name: Comment on issue with branch link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ inputs.issue_number }} \
            --body "✅ Branch \`hal9000/issue-${{ inputs.issue_number }}\` has been created. You can now create a PR from it."
