name: Hal 9000 - Execute Plan

on:
  workflow_call:
    inputs:
      language:
        description: 'Project language: python, react, java-spring'
        required: true
        type: string
      execution_model:
        description: 'LiteLLM model for execution'
        required: false
        type: string
        default: 'anthropic/claude-sonnet-4-20250514'
      test_command:
        description: 'Command to run tests'
        required: true
        type: string
      max_retries:
        description: 'Max attempts if tests fail'
        required: false
        type: number
        default: 3
      api_base:
        description: 'Custom API base URL'
        required: false
        type: string
        default: ''
    secrets:
      LLM_API_KEY:
        required: true

jobs:
  execute-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - name: Acknowledge execution
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --repo ${{ github.repository }} \
            --body "🚀 **Hal 9000** - Executing approved plan..."

      - name: Checkout consuming repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout central actions repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/hal9000-actions
          path: .hal9000
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node (for React projects)
        if: inputs.language == 'react'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Java (for Spring projects)
        if: inputs.language == 'java-spring'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Python dependencies
        run: pip install -r .hal9000/scripts/requirements.txt

      - name: Install project dependencies (Python)
        if: inputs.language == 'python'
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .; fi

      - name: Install project dependencies (React)
        if: inputs.language == 'react'
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Install project dependencies (Java Spring)
        if: inputs.language == 'java-spring'
        run: |
          if [ -f pom.xml ]; then mvn dependency:resolve; fi

      - name: Fetch plan from branch
        run: |
          PLAN_BRANCH="hal9000/plan-issue-${{ github.event.issue.number }}"
          mkdir -p .hal9000-plan
          
          # Fetch the plan branch
          git fetch origin "$PLAN_BRANCH"
          
          # Extract plan files from that branch
          git checkout "origin/$PLAN_BRANCH" -- . 2>/dev/null || git checkout "origin/$PLAN_BRANCH" -- plan.json plan_raw.md 2>/dev/null
          
          # Move to plan directory
          mv plan.json .hal9000-plan/ 2>/dev/null || true
          mv plan_raw.md .hal9000-plan/ 2>/dev/null || true
          
          # Return to main branch
          git checkout ${{ github.ref_name }} -- . 2>/dev/null || true
          
          echo "Plan fetched from branch: $PLAN_BRANCH"
          ls -la .hal9000-plan/

      - name: Fetch issue comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            --jq '[.[] | {author: .user.login, body: .body, created_at: .created_at}]' > .hal9000-comments.json

      - name: Execute plan
        id: executor
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.LLM_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.LLM_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.LLM_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .hal9000/scripts/execute_plan.py \
            --issue-number ${{ github.event.issue.number }} \
            --issue-title "${{ github.event.issue.title }}" \
            --issue-body "${{ github.event.issue.body }}" \
            --issue-comments-file ".hal9000-comments.json" \
            --plan-file ".hal9000-plan/plan.json" \
            --language ${{ inputs.language }} \
            --test-command "${{ inputs.test_command }}" \
            --max-retries ${{ inputs.max_retries }} \
            --model "${{ inputs.execution_model }}" \
            ${{ inputs.api_base && format('--api-base "{0}"', inputs.api_base) || '' }} \
            --repo-path "$(pwd)" \
            --output-dir ".hal9000-output"

      - name: Post diff comment
        if: steps.executor.outputs.success == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .hal9000/scripts/post_diff_comment.py \
            --issue-number ${{ github.event.issue.number }} \
            --output-dir ".hal9000-output" \
            --repo ${{ github.repository }}

      - name: Post failure comment
        if: steps.executor.outputs.success == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .hal9000/scripts/post_failure_comment.py \
            --issue-number ${{ github.event.issue.number }} \
            --output-dir ".hal9000-output" \
            --repo ${{ github.repository }} \
            --username "${{ github.actor }}"

      - name: Store changes in branch
        if: steps.executor.outputs.success == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANGES_BRANCH="hal9000/changes-issue-${{ github.event.issue.number }}"
          
          # Configure git
          git config user.name "Hal 9000"
          git config user.email "hal9000@github-actions.bot"
          
          # Stash current changes
          cp -r .hal9000-output /tmp/hal9000-output
          
          # Create orphan branch for changes storage
          git checkout --orphan "$CHANGES_BRANCH"
          git rm -rf . || true
          
          # Copy changes files
          cp -r /tmp/hal9000-output/* .
          
          # Commit and push
          git add -A
          git commit -m "Changes for issue #${{ github.event.issue.number }}"
          git push origin "$CHANGES_BRANCH" --force
          
          echo "Changes stored in branch: $CHANGES_BRANCH"
